# Generated by Django 5.2.7 on 2025-10-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_plans_data'),
        ('investments', '0005_delete_userwallet'),
    ]

    operations = [
    ]
