# Generated by Django 5.2.3 on 2025-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
